### ISSUE TITLE
mad cert "flag provided but not defined: -commonName"

### ISSUE THREAD

**Issue by m2acgi** [txthinking/mad#1]
`mad cert` miss the option `--commonName`

**Comment by m2acgi** [comment]
`--commonName` / `CN`, for example Google's:
![2023-11-16_11-33-37_chrome](https://github.com/txthinking/mad/assets/34497122/33911fe5-c658-49d0-8827-a3c1bddff8ca)

**Comment by txthinking** [comment]
Based on the information displayed in your screenshot, the root CA is indicated within the red box. Same with mad:

```
mad ca --ca ./ca.pem --key ./ca_key.pem --commonName "GTS CA 1C3"
```

And you want to issue a cert(cert.pem) to `www.google.com` by "GTS CA 1C3"(ca.pem)

```
mad cert --ca ./ca.pem --ca_key ./ca_key.pem --cert ./cert.pem --key ./cert_key.pem --domain www.google.com
```

Then, please inspect the cert.pem file, and it should be the same as shown in your screenshot.

> ca.pem

<img width="390" alt="image" src="https://github.com/txthinking/mad/assets/1241807/cac5c4fe-1e03-472e-8f02-5d628e8610a0">

> cert.pem

<img width="412" alt="image" src="https://github.com/txthinking/mad/assets/1241807/87a0af86-9239-4177-9651-c53b6deeb9fc">

---

BTW, the --domain parameter actually refers to the Common Name (CN). It is named as such because in typical scenarios, certificates are issued for domain names, and it also supports issuing certificates for multiple domains. mad will use the first domain specified as the value for the [Common Name](https://github.com/txthinking/mad/blob/master/cert.go#L55)

**Comment by m2acgi** [comment]
I wanna to customize the Common Name (CN) of cert. I just sent the wrong screenshot, it should be:
![2023-11-16_15-35-16_chrome](https://github.com/txthinking/mad/assets/34497122/7602e9ae-8066-42de-8cde-77bff0c01918)

I can put the domain to the first pos, thanks.
